### Análise de Risco.
#### No seu DataFrame, crie as colunas Valor_Emprestimo (ex: 10000, 5000) e Numero_Parcelas
#### Crie a coluna Comprometimento_Mensal: divida o valor do empréstimo pelo número de parcelas.
#### Filtro: Mostre apenas as linhas onde o Comprometimento_Mensal é maior que 500.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {'Nome_Usuario' : ['   JOÃO silva   ', '   miguel REMIDES   '],
       'Data_Abertura' : ['2023-05-20', '2006-07-01']
       }
df = pd.DataFrame(data)
df ['Nome_Usuario'] = df['Nome_Usuario'].str.strip().str.lower()
df['Data_Abertura'] = pd.to_datetime(df['Data_Abertura'])
df

     Nome_Usuario Data_Abertura
0      joão silva    2023-05-20
1  miguel remides    2006-07-01

In [7]:
df['Valor_Emprestimo'] = [20000, 5000]
df['Numero_Parcelas'] = [24, 12]
df

,Nome_Usuario,Data_Abertura,Valor_Emprestimo,Numero_Parcelas,Comprometimento_Mensal
0,joão silva,2023-05-20,20000,24,416.666667
1,miguel remides,2006-07-01,5000,12,416.666667

In [8]:
df['Comprometimento_Mensal'] =  df['Valor_Emprestimo']/df['Numero_Parcelas']
df

,Nome_Usuario,Data_Abertura,Valor_Emprestimo,Numero_Parcelas,Comprometimento_Mensal
0,joão silva,2023-05-20,20000,24,833.333333
1,miguel remides,2006-07-01,5000,12,416.666667

In [10]:
df[df['Comprometimento_Mensal'] > 500]

,Nome_Usuario,Data_Abertura,Valor_Emprestimo,Numero_Parcelas,Comprometimento_Mensal
0,joão silva,2023-05-20,20000,24,833.333333