### Tabela Dinâmica (Pivot Table)
#### Crie um novo DataFrame chamado df_recife com estas colunas:
##### Bairro: ['Boa Viagem', 'Boa Viagem', 'Várzea', 'Várzea', 'Centro']
##### Tipo_Credito: ['Pessoal', 'Imobiliário', 'Pessoal', 'Imobiliário', 'Pessoal']
##### Valor: [10000, 250000, 5000, 120000, 15000]
#### Use o comando df_recife.pivot_table() para criar uma tabela que mostre a soma dos valores, tendo o Bairro nas linhas (index) e o Tipo_Credito nas colunas (columns).

In [1]:
import pandas as pd
import numpy as np

In [3]:
data = {'Bairro' : ['Boa Viagem', 'Boa viagem', 'Várzea', 'Várzea', 'Várzea'], 
       'Tipo_Credito' : ['Pessoal', 'Imobiliário', 'Pessoal', 'Imobiliário', 'Pessoal'], 
       'Valor' : [10000, 250000, 5000, 120000, 15000]}
df_recife = pd.DataFrame(data)
df_recife

       Bairro Tipo_Credito   Valor
0  Boa Viagem      Pessoal   10000
1  Boa viagem  Imobiliário  250000
2      Várzea      Pessoal    5000
3      Várzea  Imobiliário  120000
4      Várzea      Pessoal   15000

In [5]:
df_recife['Bairro'] = df_recife['Bairro'].str.strip().str.title()
tabela_pivot = df_recife.pivot_table(index='Bairro', 
                                    columns='Tipo_Credito', 
                                    values='Valor', 
                                    aggfunc='sum')

tabela_pivot

Tipo_Credito  Imobiliário  Pessoal
Bairro
Boa Viagem         250000    10000
Várzea             120000    20000