### Tratamento de Strings e Datas (Limpeza)
#### Tarefa: Crie um DataFrame com uma coluna Nome_Usuario (ex: "  JOÃO silva  ") e uma coluna Data_Abertura (ex: "2023-05-#### 20").
#### Limpe o nome usando .str.strip() e deixe tudo em minúsculo com .lower().
#### Converta a coluna de data para o formato correto usando pd.to_datetime().

In [2]:
import pandas as pd
import numpy as np

In [11]:
data = {'Nome_Usuario' : ['   JOÃO silva   ', '   miguel REMIDES   '],
       'Data_Abertura' : ['2023-05-20', '2006-07-01']
       }
df = pd.DataFrame(data)
df

           Nome_Usuario Data_Abertura
0         JOÃO silva       2023-05-20
1     miguel REMIDES       2006-07-01

In [13]:
df ['Nome_Usuario'] = df['Nome_Usuario'].str.strip().str.lower()
df

     Nome_Usuario Data_Abertura
0      joão silva    2023-05-20
1  miguel remides    2006-07-01

In [16]:
df['Data_Abertura'] = pd.to_datetime(df['Data_Abertura'])
df

     Nome_Usuario Data_Abertura
0      joão silva    2023-05-20
1  miguel remides    2006-07-01

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Nome_Usuario   2 non-null      object
 1   Data_Abertura  2 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 164.0+ bytes