## O "JOIN" do Pandas (Merge)
#### Tarefa: Crie dois DataFrames: df_perfil (com colunas ID_Cliente, Nome, Renda) e df_score (com ID_Cliente, Pontuacao_Credito).
#### Ação: Use o pd.merge() para unir as duas tabelas pelo ID_Cliente. Garanta que mesmo o cliente que não tem score apareça na lista final.

In [1]:
import pandas as pd
import numpy as np

In [15]:
perfil = {
    'ID_Cliente': [101, 102, 103, 104],
    'Nome': ['Miguel Remides', 'Anna Mushchenko', 'Soraya Viviane', 'Vinicius Remides'],
    'Renda': [5000, 4500, 6000, 2000]
}

score = {
    'ID_Cliente' : [101, 102, 103], 
    'Pontuacao_Credito': [10, 9, 4]
}
df_perfil = pd.DataFrame(perfil)
df_score = pd.DataFrame(score)

In [16]:
df_perfil

   ID_Cliente              Nome  Renda
0         101    Miguel Remides   5000
1         102   Anna Mushchenko   4500
2         103    Soraya Viviane   6000
3         104  Vinicius Remides   2000

In [17]:
df_score

   ID_Cliente  Pontuacao_Credito
0         101                 10
1         102                  9
2         103                  4

In [18]:
pd.merge(df_perfil, df_score, on = 'ID_Cliente')

   ID_Cliente             Nome  Renda  Pontuacao_Credito
0         101   Miguel Remides   5000                 10
1         102  Anna Mushchenko   4500                  9
2         103   Soraya Viviane   6000                  4

In [26]:
df_final = pd.merge(df_perfil, df_score, on='ID_Cliente', how='left')
df_final

   ID_Cliente              Nome  Renda  Pontuacao_Credito
0         101    Miguel Remides   5000               10.0
1         102   Anna Mushchenko   4500                9.0
2         103    Soraya Viviane   6000                4.0
3         104  Vinicius Remides   2000                NaN

In [30]:
df_final['Pontuacao_Credito'] = df_final['Pontuacao_Credito'].fillna(0)
df_final

   ID_Cliente              Nome  Renda  Pontuacao_Credito
0         101    Miguel Remides   5000               10.0
1         102   Anna Mushchenko   4500                9.0
2         103    Soraya Viviane   6000                4.0
3         104  Vinicius Remides   2000                0.0