# DataFrames e Filtros de Crédito

##### Objetivo: Simular a estrutura do seu projeto de risco de crédito usando DataFrames e seleções condicionais.
##### Crie um DataFrame com 5 linhas e as colunas: Idade, Renda, Empréstimo e Inadimplente (True/False).
##### Crie uma nova coluna chamada Comprometimento que seja o resultado da divisão da coluna Empréstimo pela Renda.
##### Utilize o método .loc para selecionar apenas as linhas onde a Idade é superior a 25 anos.
##### Filtre o DataFrame para exibir apenas os clientes que são Inadimplente == True E possuem Renda > 3000.

In [3]:
import pandas as pd
import numpy as np

In [4]:
dados = {'Idade': [54, 28, 19, 70, 39], 
         'Renda': [5000, 2500, 1600, 8000, 4500], 
         'Empréstimo': [1000, 500, 2500, 300, 20000], 
         'Inadimplente': [True, False, False, True, False]}

In [6]:
df = pd.DataFrame(dados)
df

   Idade  Renda  Empréstimo  Inadimplente
0     54   5000        1000          True
1     28   2500         500         False
2     19   1600        2500         False
3     70   8000         300          True
4     39   4500       20000         False

In [9]:
df['Comprometimento'] = df['Empréstimo']/df['Renda']
df

   Idade  Renda  Empréstimo  Inadimplente  Comprometimento
0     54   5000        1000          True         0.200000
1     28   2500         500         False         0.200000
2     19   1600        2500         False         1.562500
3     70   8000         300          True         0.037500
4     39   4500       20000         False         4.444444

In [16]:
df.loc[df['Idade'] > 25]

   Idade  Renda  Empréstimo  Inadimplente  Comprometimento
0     54   5000        1000          True         0.200000
1     28   2500         500         False         0.200000
3     70   8000         300          True         0.037500
4     39   4500       20000         False         4.444444

In [17]:
df[(df['Inadimplente']) & (df['Renda'] > 3000)]

   Idade  Renda  Empréstimo  Inadimplente  Comprometimento
0     54   5000        1000          True           0.2000
3     70   8000         300          True           0.0375