In [2]:
import pandas as pd
import numpy as np

### Exercícios

#### Neste projeto, trabalharemos com dois arquivos csvs separados, contendo informações sobre o preço da gasolina no Brasil

##### 1. Carregue os conjuntos de dados "gasolina_2000+.csv" e "gasolina_2010+.csv" em dois DataFrames diferentes e combine-os em um único DataFrame.

In [3]:
df1 = pd.read_csv('gasolina_2000+.csv', low_memory = False)
df2 = pd.read_csv('gasolina_2010+.csv', low_memory = False)
df3 = pd.concat([df1, df2], ignore_index = True)
df3

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

##### 2. Investigue as colunas e entenda o conjunto de dados usando o head() e o info().

In [4]:
df3.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [5]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 19 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     120823 non-null  int64
 1   DATA INICIAL                   120823 non-null  str
 2   DATA FINAL                     120823 non-null  str
 3   REGIÃO                         120823 non-null  str
 4   ESTADO                         120823 non-null  str
 5   PRODUTO                        120823 non-null  str
 6   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 7   UNIDADE DE MEDIDA              120823 non-null  str
 8   PREÇO MÉDIO REVENDA            120823 non-null  float64
 9   DESVIO PADRÃO REVENDA          120823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           120823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 12  MARGEM MÉDIA REVENDA           120823 non-null  str
 13  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  str
 15  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  str
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  str
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  str
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  str
dtypes: float64(5), int64(2), str(12)
memory usage: 17.5 MB

##### 3.Selecione a terceira entrada da coluna DATA INICIAL e verifique o seu tipo.

In [6]:
df3

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [7]:
type(df3['DATA INICIAL'][2])

str

##### 4. Você deve ter percebido que as colunas DATA INICIAL e DATA FINAL estão formatadas como string. Utilizando o método pd.to_datetime, converta ambas as colunas para Timestamp / Datetime.

In [8]:
df3['DATA INICIAL'] = pd.to_datetime(df3['DATA INICIAL'])
df3['DATA FINAL'] = pd.to_datetime(df3['DATA FINAL'])
df3[['DATA INICIAL', 'DATA FINAL']].info()

<class 'pandas.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 2 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   DATA INICIAL  120823 non-null  datetime64[us]
 1   DATA FINAL    120823 non-null  datetime64[us]
dtypes: datetime64[us](2)
memory usage: 1.8 MB

##### 5.Crie uma nova coluna para representar o mês e o ano (mm-aaaa), utilizando a coluna DATA FINAL como referência.

In [9]:
df3['MÊS-ANO'] = df3['DATA FINAL'].dt.strftime('%m-%Y')
df3.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS-ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,05-2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,05-2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,05-2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,05-2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,05-2004

##### 6.Utilizando o value_counts(), liste todos os tipos de produtos contidos na base de dados.

In [10]:
df3['PRODUTO'].value_counts()

PRODUTO
GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: count, dtype: int64

##### 7. Filtre o DataFrame para obter apenas dados da 'GASOLINA COMUM'. Grave em uma nova variável.

In [11]:
df_gasolina_comum = df3[df3['PRODUTO'] == 'GASOLINA COMUM']
df_gasolina_comum

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS-ANO
9256,12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.990,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,05-2004
9257,12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.850,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,05-2004
9258,12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.000,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,05-2004
9259,12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.970,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,05-2004
9260,12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.000,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,05-2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120721,120721,2021-04-25,2021-05-01,NORTE,RORAIMA,GASOLINA COMUM,12,R$/l,5.364,0.065,5.310,5.530,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,05-2021
120722,120722,2021-04-25,2021-05-01,SUL,SANTA CATARINA,GASOLINA COMUM,119,R$/l,5.051,0.251,4.640,5.599,-99999.0,0.050,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,05-2021
120723,120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,05-2021
120724,120724,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA COMUM,34,R$/l,5.586,0.088,5.410,5.699,-99999.0,0.016,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,05-2021
120725,120725,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA COMUM,20,R$/l,5.751,0.160,5.578,6.119,-99999.0,0.028,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,05-2021

##### 8. Qual o preço médio de revenda da gasolina em agosto de 2008?

In [12]:
df3.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS-ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,05-2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,05-2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,05-2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,05-2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,05-2004

In [13]:
dados_agosto_2008 = df_gasolina_comum[df_gasolina_comum['MÊS-ANO'] == '08-2008']
preço_medio_revenda = dados_agosto_2008['PREÇO MÉDIO REVENDA'].mean()
print(f'O preço médio de revenda em agosto de 2008 foi {preço_medio_revenda:.1f}R$')

O preço médio de revenda em agosto de 2008 foi 2.6R$

##### 9. Qual o preço médio de revenda da gasolina em maio de 2014 em São Paulo?

In [14]:
dados_maio_2014 = df_gasolina_comum[df_gasolina_comum['MÊS-ANO'] == '05-2014' ]
dados_maio_2014_sp = dados_maio_2014[dados_maio_2014['ESTADO'] == 'SAO PAULO']
preço_medio2 = dados_maio_2014_sp['PREÇO MÉDIO REVENDA'].mean()
print(f'O preço médio de revenda da gasolina em maio de 2014 em São Paulo foi de {preço_medio2:.1f}R$')

O preço médio de revenda da gasolina em maio de 2014 em São Paulo foi de 2.9R$

##### 10. Você conseguiria descobrir em qual(quais) estado(s) a gasolina ultrapassou a barreira dos 5,00 R$? E quando isso occorreu?

In [15]:
df_gasolina_maior_5 = df_gasolina_comum[df_gasolina_comum['PREÇO MÉDIO REVENDA'] > 5]
df_gasolina_maior_5['ESTADO'].value_counts()

ESTADO
ACRE                   60
RIO DE JANEIRO         34
TOCANTINS              20
RIO GRANDE DO NORTE    14
DISTRITO FEDERAL       12
ALAGOAS                11
BAHIA                  11
CEARA                  11
MATO GROSSO DO SUL     11
MINAS GERAIS           11
PARA                   11
PIAUI                  11
RIO GRANDE DO SUL      11
AMAZONAS               10
ESPIRITO SANTO         10
GOIAS                  10
MARANHAO               10
PERNAMBUCO             10
RONDONIA               10
SANTA CATARINA         10
SERGIPE                10
PARAIBA                 9
MATO GROSSO             9
PARANA                  9
RORAIMA                 9
SAO PAULO               9
Name: count, dtype: int64

##### 11. Qual a média de preços dos estados da região sul em 2012?

In [16]:
df_sul = df3[df3['REGIÃO'] == 'SUL']
df_sul_gasolina = df_sul[df_sul['PRODUTO'] == 'GASOLINA COMUM']
df_sul_gasolina_2012 = df_sul_gasolina[df_sul_gasolina['DATA FINAL'].dt.year == 2012]
preço_medio_sul = df_sul_gasolina_2012['PREÇO MÉDIO REVENDA'].mean()
print(f'O preço médio da gasolina nos estados da região Sul em 2012 é igual a {preço_medio_sul:.1f}R$.')

O preço médio da gasolina nos estados da região Sul em 2012 é igual a 2.7R$.

##### 12. Você conseguiria obter uma tabela contendo a variação percentual ano a ano para o estado do Rio de Janeiro?

In [31]:
df_rj = df_gasolina_comum[df_gasolina_comum['ESTADO'] == 'RIO DE JANEIRO']
precos_anuais = df_rj.groupby(df_rj['DATA FINAL'].dt.year)['PREÇO MÉDIO REVENDA'].mean()
variacao_percentual = precos_anuais.pct_change() * 100
tabela_variacao = (variacao_percentual.to_frame(name = 'VARIAÇÃO %')).style.format("{:.2f}%")
tabela_variacao

##### Desafio: Crie uma tabela contendo a séria temporal com a diferença absoluta e percentual entre os valores mais baratos e caros. Apresente também ao lado os estados na qual os maiores e os menores preços foram registrados.

In [35]:
idx_min = df_gasolina_comum.groupby('MÊS-ANO')['PREÇO MÉDIO REVENDA'].idxmin()
idx_max = df_gasolina_comum.groupby('MÊS-ANO')['PREÇO MÉDIO REVENDA'].idxmax()

df_desafio = pd.DataFrame()
df_desafio['Mês'] = df_gasolina_comum.loc[idx_min, 'MÊS-ANO'].values
df_desafio['Preço Mínimo'] = df_gasolina_comum.loc[idx_min, 'PREÇO MÉDIO REVENDA'].values
df_desafio['Estado (Mín)'] = df_gasolina_comum.loc[idx_min, 'ESTADO'].values
df_desafio['Preço Máximo'] = df_gasolina_comum.loc[idx_max, 'PREÇO MÉDIO REVENDA'].values
df_desafio['Estado (Máx)'] = df_gasolina_comum.loc[idx_max, 'ESTADO'].values

df_desafio['Diferença Absoluta'] = df_desafio['Preço Máximo'] - df_desafio['Preço Mínimo']
df_desafio['Diferença %'] = (df_desafio['Diferença Absoluta'] / df_desafio['Preço Mínimo']) * 100

display(df_desafio.head(10))

,Mês,Preço Mínimo,Estado (Mín),Preço Máximo,Estado (Máx),Diferença Absoluta,Diferença %
0,01-2005,2.151,DISTRITO FEDERAL,2.737,MATO GROSSO,0.586,27.243143
1,01-2006,2.383,SAO PAULO,2.938,MATO GROSSO,0.555,23.289971
2,01-2007,2.356,AMAZONAS,2.946,MATO GROSSO,0.590,25.042445
3,01-2008,2.364,AMAZONAS,2.966,ACRE,0.602,25.465313
4,01-2009,2.396,CEARA,2.976,ACRE,0.580,24.207012
5,01-2010,2.412,PARAIBA,2.966,ACRE,0.554,22.968491
6,01-2011,2.436,PARAIBA,3.045,ACRE,0.609,25.000000
7,01-2012,2.568,PIAUI,3.126,ACRE,0.558,21.728972
8,01-2013,2.625,PIAUI,3.133,ACRE,0.508,19.352381
9,01-2014,2.783,PIAUI,3.383,ACRE,0.600,21.559468