# Agrupamento de Vendas (BI Style)

#### Objetivo: Aplicar o Groupby para gerar insights de negócio, como em uma vaga de BI.
#### Use o dataset abaixo para o exercício:

In [12]:
import pandas as pd
data = {
    'Regiao': ['Norte', 'Norte', 'Sul', 'Sul', 'Centro', 'Centro'],
    'Vendedor': ['Ana', 'Bruno', 'Caio', 'Duda', 'Elias', 'Fernanda'],
    'Vendas': [2500, 1800, 3200, 4100, 1500, 2900],
    'Metas_Batidas': [1, 0, 1, 1, 0, 1]
}
df = pd.DataFrame(data)

#### Agrupe os dados por Regiao.
#### Calcule a soma total de vendas por região, garantindo que apenas colunas numéricas sejam somadas (numeric_only=True).
#### Calcule a média de vendas por região.
#### Insight: Qual região teve o maior valor individual de venda?

In [13]:
df

   Regiao  Vendedor  Vendas  Metas_Batidas
0   Norte       Ana    2500              1
1   Norte     Bruno    1800              0
2     Sul      Caio    3200              1
3     Sul      Duda    4100              1
4  Centro     Elias    1500              0
5  Centro  Fernanda    2900              1

In [14]:
df.groupby('Regiao')

In [31]:
df.groupby('Regiao')[['Vendas']].sum(numeric_only = True)

        Vendas
Regiao
Centro    4400
Norte     4300
Sul       7300

In [30]:
df.groupby('Regiao')[['Vendas']].mean(numeric_only = True)

        Vendas
Regiao
Centro  2200.0
Norte   2150.0
Sul     3650.0

In [21]:
df

   Regiao  Vendedor  Vendas  Metas_Batidas
0   Norte       Ana    2500              1
1   Norte     Bruno    1800              0
2     Sul      Caio    3200              1
3     Sul      Duda    4100              1
4  Centro     Elias    1500              0
5  Centro  Fernanda    2900              1

In [29]:
 df.groupby('Regiao')[['Vendas']].max()

        Vendas
Regiao
Centro    2900
Norte     2500
Sul       4100